typography_spectrum: 0.9078005545306951
color:
  brandStrength: 0.5269875302910805
  lightness: 0.6547714320477098
  saturation: 0.6462305723689497
  rhythmicContrast: 0.61645423527807
  brandColors:
    - '#EFEDEE'
    - '#010000'
    - '#7B7A78'
    - '#4F4E4E'
    - '#007200'
layout_spectrum: 0.1918481681495905
name: Mike John Otto
title: M/ke John Otto
description: all my sites & content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/938739fb-aad5-4efb-bb43-8983ef82ab11.png
