typography_spectrum: 0.3929034066386521
color:
  brandStrength: 0.1104254296515137
  lightness: 0.8472372777760029
  saturation: 0.5693116637412459
  rhythmicContrast: 0.8098119178321213
  brandColors:
    - '#FFFFFF'
    - '#EA202D'
    - '#0E0E0E'
    - '#ACA299'
    - '#EF666D'
layout_spectrum: 0.5430090574081987
name: Mike John Otto
title: M/ke John Otto
description: all my sites & content
