typography_spectrum: 0.5743792003486305
color:
  brandStrength: 0.10930547444149852
  lightness: 0.813701489707455
  saturation: 0.8641200989950448
  rhythmicContrast: 0.04104744270443916
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.7054670955985785
name: Mike John Otto
title: M/ke John Otto
description: all my sites & content
